# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180126_0927'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='leader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='leading', to='users.User'),
            preserve_default=False,
        ),
    ]
